name: Payment Service CI

on:
  push:
    paths:
      - '**/app.py'
      - '**/Dockerfile'
      - '**/docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t payment-service .
